<?php

namespace WorldFactory\QQ\Extensions\Pdo;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class QQExtensionsPdoBundle extends Bundle
{
    public function getContainerExtension()
    {
        return parent::getContainerExtension(); // TODO: Change the autogenerated stub
    }
}
